/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_dynamodb_all_tables_region": "us-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Users",
            "region": "us-west-1"
        },
        {
            "tableName": "Groceries",
            "region": "us-west-1"
        },
        {
            "tableName": "Pantries",
            "region": "us-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "intelligroceryAPI",
            "endpoint": "https://m9fqyfu6g0.execute-api.us-west-1.amazonaws.com/dev",
            "region": "us-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-1:4a88e20d-35d7-4cc7-a68f-a67b20c5ba93",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_nxEWMtKN5",
    "aws_user_pools_web_client_id": "72tml7htihosebgukqma3b0rl",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
